spring:
  datasource:
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  url: jdbc:postgresql://localhost:5432/lolskins

  liquibase:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: lolskins
        check_nullability: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

lol:
  lockfile-path: "/Applications/League of Legends.app/Contents/LoL/lockfile"
  image-dir: "./data/images/skins"
  ddragon-base: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash"
